# Generated by Django 3.0.6 on 2025-04-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='modified_by',
        ),
    ]
